version: "3.7"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"

    ports:
      - "3000:3000"
    
    command: npm start
    
    networks: 
      - test-net
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend"

    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - ENDPOINT=http://0.0.0.0:8000/api/requests-loan/
      - SECRET_KEY=7d@1v(esv5f75z=k25(6@md7q4reb$w$j8e2c2o^1w+7rpwgks
      - ENGINE=django.db.backends.postgresql
      - NAME=DB_TEST
      - USER=postgres
      - PASSWORD=postgres
      - HOST=127.0.0.1:5432
      - PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - back_data:/backend
    command: python3 manage.py runserver 0.0.0.0:8000

    networks: 
      - test-net
  
  db:
    image: "postgres:12"
    container_name: db

    ports: 
      - "5432:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - db_data:/var/lib/postgresql/data

    networks: 
      - test-net

volumes:
  back_data:
  db_data:

networks:
  test-net: