name: Deploy EKS

on:
  push:
    branches:
      - main

jobs:
  push_to-registry:
    name: push image a dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: push a dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jsmat/curso-devops
        tag_with_ref: true
        tag_with_sha: true
        tags: latest, ${{ github.sha }}